name: golangci-lint

on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
          # Optional: show only new issues if it's a pull request
          only-new-issues: ${{ github.event_name == 'pull_request' }}
